---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vinlab-viewer-deployment
  namespace: vinlab
spec:
  selector:
    matchLabels:
      app: vinlab-viewer
  replicas: 1
  template:
    metadata:
      labels:
        app: vinlab-viewer
    spec:
      containers:
        - name: vinlab-viewer
          image: vindr/vinlab-viewer
          ports:
            - containerPort: 80
              name: viewer-port
          env:
            - name: SERVER_BASE_URL
              value: "http://localhost:8080"
            - name: MEDICAL_VIEWER_URL_PREFIX
              value: "/medical-view"
            - name: DASHBOARD_URL_PREFIX
              value: "/dashboard"
            - name: OIDC_CLIENT_ID
              value: "vinlab-frontend"
            - name: OIDC_AUTHORIZATION_URI
              value: "http://localhost:8080/realms/vinlab/protocol/openid-connect/auth"
            - name: OIDC_ACCESS_TOKEN_URI
              value: "http://localhost:8080/realms/vinlab/protocol/openid-connect/token"
            - name: OIDC_REDIRECT_URI
              value: "http://localhost:8080/dashboard"
            - name: OIDC_LOGOUT_URI
              value: "http://localhost:8080/realms/vinlab/protocol/openid-connect/logout"
            - name: OIDC_USERINFO_ENDPOINT
              value: "http://localhost:8080/realms/vinlab/protocol/openid-connect/userinfo"
            - name: OIDC_AUDIENCE
              value: "vinlab-backend"
          resources:
            limits:
              memory: "512Mi"
            requests:
              memory: "256Mi"
      imagePullSecrets:
        - name: vindr-ecr
---
apiVersion: v1
kind: Service
metadata:
  name: viewer
  namespace: vinlab
spec:
  selector:
    app: vinlab-viewer
  ports:
    - port: 80
      targetPort: 80
